//App actions
export const APP_SHOW_LOADING = "APP_SHOW_LOADING";
export const APP_HIDE_LOADING = "APP_HIDE_LOADING";
export const APP_ENQUEUE_SNACKBAR = "APP_ENQUEUE_SNACKBAR";
export const APP_REMOVE_SNACKBAR = "APP_REMOVE_SNACKBAR";
export const APP_OPEN_LEFT_SIDEBAR = "APP_OPEN_LEFT_SIDEBAR";
export const APP_CLOSE_LEFT_SIDEBAR = "APP_CLOSE_LEFT_SIDEBAR";
export const APP_SET_MOBILE = "APP_SET_MOBILE";

//Types actions
export const TYPES_SET_LOADING = "TYPES_SET_LOADING";
export const TYPES_SET_TYPES = "TYPES_SET_TYPES";
export const TYPES_SET_SOURCES = "TYPES_SET_SOURCES";
export const TYPES_SET_SOURCES_LOADING = "TYPES_SET_SOURCES_LOADING";

//CurrentUser actions
export const CURRENT_USER_INITIAL_LOAD = "CURRENT_USER_INITIAL_LOAD";
export const CURRENT_USER_SET_LOADING = "CURRENT_USER_SET_LOADING";
export const CURRENT_USER_SET_CURRENT_USER = "CURRENT_USER_SET_CURRENT_USER";